databaseChangeLog:
  - changeSet:
      id: 1
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Country
            columns:
              - column:
                  name: CountryIso
                  type: varchar(3)
              - column:
                  name: CountryIsoName
                  type: varchar(100)
              - column:
                  name: CountryName
                  type: varchar(100)
              - column:
                  name: CountryContinent
                  type: varchar(20)
              - column:
                  name: CountryMinX
                  type: double
              - column:
                  name: CountryMinY
                  type: double
              - column:
                  name: CountryMaxX
                  type: double
              - column:
                  name: CountryMaxY
                  type: double
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 2
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Language
            columns:
              - column:
                  name: LangIsoCode
                  type: varchar(3)
              - column:
                  name: LangIsoName
                  type: varchar(50)
              - column:
                  name: LangLocalName
                  type: varchar(50)
              - column:
                  name: LangStatus
                  type: integer
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 3
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Event
            columns:
              - column:
                  name: EventId
                  type: varchar(50)
              - column:
                  name: LangIsoCode
                  type: varchar(3)
              - column:
                  name: RegionId
                  type: varchar(50)
              - column:
                  name: EventName
                  type: varchar(50)
              - column:
                  name: EventDesc
                  type: text
              - column:
                  name: EventActive
                  type: integer
              - column:
                  name: EventPredefined
                  type: integer
              - column:
                  name: EventRGBColor
                  type: varchar(10)
              - column:
                  name: EventKeyWords
                  type: text
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 4
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Cause
            columns:
              - column:
                  name: CauseId
                  type: varchar(50)
              - column:
                  name: LangIsoCode
                  type: varchar(3)
              - column:
                  name: RegionId
                  type: varchar(50)
              - column:
                  name: CauseName
                  type: varchar(50)
              - column:
                  name: CauseDesc
                  type: text
              - column:
                  name: CauseActive
                  type: integer
              - column:
                  name: CausePredefined
                  type: integer
              - column:
                  name: CauseRGBColor
                  type: varchar(10)
              - column:
                  name: CauseKeyWords
                  type: text
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 5
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Dictionary
            columns:
              - column:
                  name: DictLabelId
                  type: integer
              - column:
                  name: LangIsoCode
                  type: varchar(3)
              - column:
                  name: DictTranslation
                  type: varchar(30)
              - column:
                  name: DictTechHelp
                  type: varchar(50)
              - column:
                  name: DictBasDesc
                  type: text
              - column:
                  name: DictFullDesc
                  type: text
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 6
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: LabelGroup
            columns:
              - column:
                  name: DictLabelId
                  type: integer
              - column:
                  name: LGName
                  type: varchar(50)
              - column:
                  name: LabelName
                  type: varchar(30)
              - column:
                  name: LGOrder
                  type: integer
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 7
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Info
            columns:
              - column:
                  name: InfoKey
                  type: varchar(50)
              - column:
                  name: InfoValue
                  type: varchar(1024)
              - column:
                  name: InfoAuxValue
                  type: varchar(1024)
              - column:
                  name: RecordCreation
                  type: datetime
              - column:
                  name: RecordSync
                  type: datetime
              - column:
                  name: RecordUpdate
                  type: datetime
  - changeSet:
      id: 8
      author: jhcaiced
      context: legacy
      changes:
        - createTable:
            tableName: Sync
            columns:
              - column:
                  name: SyncId
                  type: varchar(50)
              - column:
                  name: RegionId
                  type: varchar(50)
              - column:
                  name: SyncTable
                  type: varchar(100)
              - column:
                  name: SyncUpload
                  type: datetime
              - column:
                  name: SyncDownload
                  type: datetime
              - column:
                  name: SyncURL
                  type: varchar(1024)
              - column:
                  name: SyncSpec
                  type: varchar(1024)
