version: '2'
services:
  web:
    image: "desinventar/online:latest"
    build: .
    ports:
     - "8081:80"
    volumes:
     - .:/usr/share/desinventar
  devel:
    image: "desinventar/online:latest"
    depends_on:
    - web
    - redis
    ports:
     - "8080:80"
    volumes:
     - .:/usr/share/desinventar
     - /var/lib/desinventar:/var/lib/desinventar
  redis:
    build: docker/redis
    ports:
    - "8090:6379"
