version: '3'
services:
  web:
    build: .
    image: desinventar/online:latest
    ports:
      - "8080:80"
    environment:
      - DESINVENTAR_FLAGS_MODE
      - DESINVENTAR_MODE
      - DESINVENTAR_PATHS_CACHEDIR
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    ports:
      - "8090:80"
    environment:
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
      - DESINVENTAR_PORTAL_CACHEDIR
      - TEST_PORTAL_URL
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
  test:
    build:
      context: .
      dockerfile: docker/e2e-test/Dockerfile
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
