version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: desinventar/online:latest
    command: bash -c '(/opt/app/node_modules/.bin/webpack --display-error-details --watch &) && (/usr/sbin/httpd -D FOREGROUND)'
    ports:
      - "8080:80"
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
    environment:
      - NODE_ENV
      - APP_ENV
      - DESINVENTAR_FLAGS_MODE
      - DESINVENTAR_MODE
      - DESINVENTAR_PATHS_CACHEDIR
      - DESINVENTAR_DEBUG_REQUEST
      - DESINVENTAR_DEBUG_RESPONSE
  devel:
    build:
      context: .
      dockerfile: Dockerfile
    image: desinventar/online:latest
    command: bash -c '(/opt/app/node_modules/.bin/webpack --display-error-details --watch &) && (/usr/sbin/httpd -D FOREGROUND)'
    ports:
      - "8081:80"
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
      - /var/local/desinventar:/var/local/desinventar
    environment:
      - NODE_ENV
      - APP_ENV
      - DESINVENTAR_FLAGS_MODE
      - DESINVENTAR_MODE
      - DESINVENTAR_PATHS_CACHEDIR
      - DESINVENTAR_DEBUG_REQUEST
      - DESINVENTAR_DEBUG_RESPONSE
  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    command: bash -c '(/opt/app/node_modules/.bin/webpack --display-error-details --watch &) && (/usr/sbin/httpd -D FOREGROUND)'
    ports:
      - "8090:80"
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
    environment:
      - NODE_ENV
      - APP_ENV
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
      - DESINVENTAR_PORTAL_CACHEDIR
      - TEST_PORTAL_URL
  liquibase:
    build:
      context: .
      dockerfile: docker/liquibase/Dockerfile
    volumes:
      - .:/opt/app
  http:
    build:
      context: .
      dockerfile: docker/http/Dockerfile
    ports:
      - "8082:80"
    volumes:
      - .:/opt/app
      - ./files/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - /var/local/desinventar:/var/local/desinventar
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/opt/app
      - ./files/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - /opt/app/vendor
      - /opt/app/node_modules
      - /var/local/desinventar:/var/local/desinventar
    environment:
      - DESINVENTAR_PATHS_CACHEDIR
      - DESINVENTAR_MAPS_FONTS_DIR=/usr/share/fonts/truetype/liberation/fonts.txt
  mapserver:
    build:
      context: .
      dockerfile: docker/mapserver/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/local/desinventar:/var/local/desinventar
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
