version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/usr/share/desinventar
     - /usr/share/desinventar/vendor
  devel:
    image: "desinventar/online:latest"
    depends_on:
    - web
    ports:
     - "8081:80"
    volumes:
     - .:/usr/share/desinventar
     - /var/local/desinventar:/var/local/desinventar
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./portal:/opt/portal
      - /opt/portal/vendor
    environment:
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
