version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/usr/share/desinventar
     - /usr/share/desinventar/vendor
    environment:
    - DESINVENTAR_FLAGS_MODE
  devel:
    build: .
    depends_on:
    - web
    ports:
     - "8081:80"
    volumes:
     - .:/usr/share/desinventar
     - /usr/share/desinventar/vendor
     - /var/local/desinventar:/var/local/desinventar
    environment:
    - DESINVENTAR_FLAGS_MODE
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./portal:/opt/web
      - /opt/web/vendor
    environment:
      - DESINVENTAR_URL
