version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - DESINVENTAR_FLAGS_MODE
      - DESINVENTAR_MODE
      - DESINVENTAR_PATHS_CACHEDIR
  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    ports:
      - "8090:80"
    environment:
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
      - DESINVENTAR_PORTAL_CACHEDIR
      - TEST_PORTAL_URL
  test:
    build:
      context: .
      dockerfile: docker/e2e-test/Dockerfile
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
