version: '2'
services:
  web:
    image: "desinventar/online:latest"
    build: .
    ports:
     - "8081:80"
    volumes:
     - .:/usr/share/desinventar
  devel:
    image: "desinventar/online:latest"
    depends_on:
    - web
    ports:
     - "8080:80"
    volumes:
     - .:/usr/share/desinventar
     - /var/lib/desinventar:/var/lib/desinventar
  test-unit:
    image: desinventar/online:latest
    depends_on:
      - web
    volumes_from:
      - web
    entrypoint: make test-unit
  test-web:
    image: desinventar/online:latest
    depends_on:
      - web
    volumes_from:
      - web
    entrypoint: make composer-autoload test-web
    environment:
    - DESINVENTAR_URL=http://desinventaronline_web_1/
    - DESINVENTAR_WDHOST=http://desinventaronline_hub_1:4444/wd/hub
  hub:
    image: selenium/standalone-chrome:3.4.0-dysprosium
