version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: desinventar/online:latest
    volumes:
      - /opt/app/vendor
      - /opt/app/node_modules
      - /opt/app/backend/express/node_modules
    environment:
      - NODE_ENV
      - APP_ENV
      - DESINVENTAR_FLAGS_MODE
      - DESINVENTAR_MODE
      - DESINVENTAR_LOGGER_FILE
      - DESINVENTAR_LOGGER_LEVEL
      - DESINVENTAR_PATHS_CACHEDIR
      - DESINVENTAR_DEBUG_REQUEST
      - DESINVENTAR_DEBUG_RESPONSE
      - DESINVENTAR_MAPS_USE_REMOTE_LAYERS
      - DESINVENTAR_MAPS_GOOGLE_API_KEY
  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    ports:
      - "8090:80"
    volumes:
      - /opt/app/vendor
      - /opt/app/node_modules
    environment:
      - NODE_ENV
      - APP_ENV
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
      - DESINVENTAR_PORTAL_CACHEDIR
      - TEST_PORTAL_URL
      - DESINVENTAR_LOGGER_FILE
      - DESINVENTAR_LOGGER_LEVEL
  test:
    build:
      context: .
      dockerfile: docker/e2e-test/Dockerfile
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
