version: '2.2'
services:
  web:
    image: "desinventar/online:latest"
    build: .
    environment:
      - NODE_ENV=default
  portal:
    build:
      context: .
      dockerfile: portal/Dockerfile
    environment:
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
      - DESINVENTAR_PORTAL_CACHEDIR
      - TEST_PORTAL_URL
  test:
    build:
      context: .
      dockerfile: docker/e2e-test/Dockerfile
    command: php -S localhost:80
