version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
      - /opt/app/portal/vendor
      - /opt/app/portal/node_modules
    environment:
    - DESINVENTAR_FLAGS_MODE
    - DESINVENTAR_MODE
    - DESINVENTAR_CACHEDIR
  devel:
    build: .
    command: bash -c '(/opt/app/node_modules/.bin/webpack --display-error-details --watch &) && (/usr/sbin/httpd -D FOREGROUND)'
    depends_on:
    - web
    ports:
      - "8081:80"
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
      - /opt/app/portal/vendor
      - /opt/app/portal/node_modules
      - /var/local/desinventar:/var/local/desinventar
    environment:
    - DESINVENTAR_FLAGS_MODE
    - DESINVENTAR_MODE
    - DESINVENTAR_CACHEDIR
  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    command: bash -c '(/opt/app/portal/node_modules/.bin/webpack --display-error-details --watch &) && (/usr/sbin/httpd -D FOREGROUND)'
    ports:
      - "8090:80"
    volumes:
      - .:/opt/app
      - /opt/app/vendor
      - /opt/app/node_modules
      - /opt/app/portal/vendor
      - /opt/app/portal/node_modules
    environment:
      - DESINVENTAR_MODE
      - DESINVENTAR_URL
      - DESINVENTAR_PORTAL_CACHEDIR
      - TEST_PORTAL_URL

