version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network desinventar_default \
              appropriate/curl --retry 30 --retry-delay 2 --retry-connrefused http://web:80/api
      - run:
          name: Running Tests
          command: |
            docker-compose exec web sh -c 'make test'
      - run:
          name: Running e2e Tests
          command: |
            set -x
            if [ $CIRCLE_BRANCH = 'develop' ]; then \
              docker build -t desinventar/e2e-test -f docker/e2e-test/Dockerfile . ; \
              docker run --network desinventar_default \
                desinventar/e2e-test:latest sh -c 'TEST_WEB_URL=http://web:80 make test-web'; \
            fi
