version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker-compose-circleci.yml up -d
            docker run --network desinventar_default \
              appropriate/curl --retry 30 --retry-delay 2 --retry-connrefused http://web:80/api
      - run:
          name: Running Tests
          command: |
            docker-compose -f docker-compose-circleci.yml exec web sh -c 'make test-unit test-api'
      - run:
          name: Running e2e Tests
          command: |
            set -x
            docker build -t desinventar/e2e-test -f docker/e2e-test/Dockerfile . ; \
            docker run --network desinventar_default \
              desinventar/e2e-test:latest sh -c 'TEST_WEB_URL=http://web:80 make test-e2e'
