CLEAR
CLOSE DATABASES

USE MAR_ADM1 IN 0 ALIAS ADM1
USE MAR_ADM2 IN 0 ALIAS ADM2
USE MAR_ADM3 IN 0 ALIAS ADM3
USE MAR_ADM4 IN 0 ALIAS ADM4

*ALTER TABLE ADM1 ADD COLUMN NCODIGO1 VARCHAR(30)
*ALTER TABLE ADM2 ADD COLUMN NCODIGO1 VARCHAR(30)
*ALTER TABLE ADM2 ADD COLUMN NCODIGO2 VARCHAR(30)
*ALTER TABLE ADM3 ADD COLUMN NCODIGO1 VARCHAR(30)
*ALTER TABLE ADM3 ADD COLUMN NCODIGO2 VARCHAR(30)
*ALTER TABLE ADM3 ADD COLUMN NCODIGO3 VARCHAR(30)
*ALTER TABLE ADM4 ADD COLUMN NCODIGO1 VARCHAR(30)
*ALTER TABLE ADM4 ADD COLUMN NCODIGO2 VARCHAR(30)
*ALTER TABLE ADM4 ADD COLUMN NCODIGO3 VARCHAR(30)
*ALTER TABLE ADM4 ADD COLUMN NCODIGO4 VARCHAR(30)

UPDATE ADM1 SET NCODIGO1=TRIM(STR(ID_1))

SELECT ADM1
NREC1=RECCOUNT()
FOR I1 = 1 TO NREC1
	SELECT ADM1
	GOTO I1
	COD1 = ALLTRIM(NCODIGO1)
	MID_1 = ID_1
	SELECT * FROM ADM2 WHERE ID_1=MID_1 INTO CURSOR C2
	NREC2 = RECCOUNT()
	FOR I2 = 1 TO NREC2
		SELECT C2
		GOTO I2
		MID_2 = ID_2
		COD2 = COD1 + PADL(ALLTRIM(STR(I2)),2,"0")
		UPDATE ADM2 SET NCODIGO1=COD1,NCODIGO2=COD2 WHERE ID_2=MID_2
		SELECT * FROM ADM3 WHERE ID_2=MID_2 INTO CURSOR C3
		NREC3 = RECCOUNT()
		FOR I3 = 1 TO NREC3
			SELECT C3
			GOTO I3
			MID_3 = ID_3
			COD3 = COD2 + PADL(ALLTRIM(STR(I3)),2,"0")
			* ? I1, NREC1, COD1, NREC2, I2, COD2, I3, COD3
			UPDATE ADM3 SET NCODIGO1=COD1,NCODIGO2=COD2,NCODIGO3=COD3 WHERE ID_3=MID_3
			SELECT * FROM ADM4 WHERE ID_3=MID_3 INTO CURSOR C4
			NREC4 = RECCOUNT()
			FOR I4 = 1 TO NREC4
				SELECT C4
				GOTO I4
				MID_4 = ID_4
				COD4 = COD3 + PADL(ALLTRIM(STR(I4)),2,"0")
				? I1, NREC1, COD1, NREC2, I2, COD2, I3, COD3, I4, COD4
				UPDATE ADM4 SET NCODIGO1=COD1,NCODIGO2=COD2,NCODIGO3=COD3,NCODIGO4=COD4 WHERE ID_4=MID_4
			ENDFOR
		ENDFOR
	ENDFOR
ENDFOR
CLOSE DATABASES
