const db = require('../helpers/DatabaseHelper')

exports.up = async function(knex) {
  await db.createTable(knex, 'Queries', table => {
    table.string('QueryId', 50)
    table.string('RegionId', 50)
    table.string('SessionId', 50)
    table.string('UserId', 20)
    table.string('QueryStatus', 20)
    table.datetime('QueryDate')
    table.string('QueryName', 100)
    table.text('QueryContent')
  })
  await db.createTable(knex, 'Region', table => {
    table.string('RegionId', 50)
    table.string('RegionLabel', 200)
    table.string('LangIsoCode', 3)
    table.string('CountryIso', 3)
    table.integer('RegionOrder')
    table.integer('RegionStatus')
    table.datetime('RegionLastUpdate')
    table.integer('IsCRegion')
    table.integer('IsVRegion')
  })
  await db.createTable(knex, 'RegionAuth', table => {
    table.string('UserId', 20)
    table.string('RegionId', 50)
    table.string('AuthKey', 50)
    table.integer('AuthValue')
    table.string('AuthAuxValue', 1024)
  })
  await db.createTable(knex, 'RegionItem', table => {
    table.string('RegionId', 50)
    table.string('RegionItem', 50)
    table.string('RegionQuery', 50)
  })
  await db.createTable(knex, 'User', table => {
    table.string('UserId', 20)
    table.string('UserEMail', 100)
    table.string('UserPasswd', 100)
    table.string('UserFullName', 100)
    table.string('Organization', 100)
    table.string('CountryIso', 3)
    table.string('UserCity', 50)
    table.datetime('UserCreationDate')
    table.text('UserNotes')
    table.integer('UserActive')
  })
  await db.createTable(knex, 'UserLockList', table => {
    table.string('SessionId', 50)
    table.string('TableId', 50)
    table.string('RecordId', 50)
    table.datetime('LastUpdate')
  })
  await db.createTable(knex, 'UserOption', table => {
    table.string('UserId', 20)
    table.string('OptionKey', 50)
    table.string('OptionValue', 1024)
    table.string('OptionAuxValue', 1024)
  })
  await db.createTable(knex, 'UserSession', table => {
    table.string('SessionId', 50)
    table.string('RegionId', 50)
    table.string('UserId', 20)
    table.integer('Valid')
    table.datetime('Start')
    table.datetime('LastUpdate')
    table.string('LangIsoCode', 3)
  })
}

exports.down = async function(knex) {
  await db.dropTable(knex, 'Queries')
  await db.dropTable(knex, 'Region')
  await db.dropTable(knex, 'RegionAuth')
  await db.dropTable(knex, 'RegionItem')
  await db.dropTable(knex, 'User')
  await db.dropTable(knex, 'UserLockList')
  await db.dropTable(knex, 'UserOption')
  await db.dropTable(knex, 'UserSession')
}
